// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scyuaftfitgapwlgjaym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjeXVhZnRmaXRnYXB3bGdqYXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTQyMjEsImV4cCI6MjA1ODEzMDIyMX0.t34uTHw8iW8enhKn7ohhEdJsRlMtbEPi_A8ylSnOWyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);